// Code generated by goctl. DO NOT EDIT.
package types

type AccessShortUrlRequest struct {
}

type AccessShortUrlResponse struct {
}

type CreatShortUrlResponse struct {
}

type CreateShortUrlRequest struct {
}

type DetailShortUrlRequest struct {
}

type DetailShortUrlResponse struct {
}
