// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	shorturl "github.com/colinrs/goshorturl/internal/handler/shorturl"
	"github.com/colinrs/goshorturl/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/shorturl/access",
				Handler: shorturl.AccessShortUrlHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/shorturl/create",
				Handler: shorturl.CreateShortUrlHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/shorturl/detail",
				Handler: shorturl.DetailShortUrlHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
